### ISSUE TITLE
CPU usage - different values reported by SwiftMetrics and Activity Monitor (macOS)

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#1]
Raised from 

https://github.com/IBM-Swift/SwiftMetrics/issues/51

**Comment by stalleyj** [comment]
@rolivieri 
The SwiftMetrics cpu usage value is a % per physical processor. We are retrieving the usage using getrusage and dividing this by the number of processors but this is returned as a value between 0 and 1 so you need to multiply by 100 to get a percentage.

**Comment by rolivieri** [comment]
@stalleyj Thanks for the clarification. In that case, the values are matching and it is working as designed. @thesounddefense - See response above.

**Comment by tobespc** [comment]
closing issues as working as designed
