### ISSUE TITLE
Modify websockets to use wss rather than ws

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#111]
Raised by @rolivieri  

Can you try using wss for the web socket connections instead of ws? That's what our demo app is doing for establishing secured web connections with the kitura server. Customers may want that instead of plain http. :slightly_smiling_face: In our demo app code, we use ws for localhost connections and wss for websocket connections when running on bluemix.

**Comment by sjanuary** [comment]
Kitura-Websocket states that "To enable WSS simply set up your Kitura based server for SSL/TLS support."  It doesn't seem like there's a different API or anything, so if SwiftMetricsDash is initialised with an existing `Router` from a Kitura server that has SSL/TLS set up then I think it should already be using WSS.

**Comment by sjanuary** [comment]
So I think we just need to change the dashboard to use wss on the client side if SwiftMetricsDash is using wss.
