### ISSUE TITLE
Using version 1.7 of Kitura

### ISSUE THREAD

**Issue by crspybits** [RuntimeTools/SwiftMetrics#129]
I'm using version 1.7 of Kitura:

        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),

I'd like to use SwiftMetrics. Any idea when your package will be updated from 1.6?

Thanks,
Chris

**Comment by tobespc** [comment]
We pull kitura 1.7 in when building for Swift 3.1

**Comment by tobespc** [comment]
Package@swift-3.1.1.swift

**Comment by crspybits** [comment]
Thanks @tobespc! Just needed to run `sudo xcode-select -s /Applications/Xcode-8.3.app/Contents/Developer` on my system and it made the Swift Package Manager happy!
