### ISSUE TITLE
Hide 'System Memory' in Dashboard

### ISSUE THREAD

**Issue by Bersaelor** [RuntimeTools/SwiftMetrics#141]
Is there a way I can hide the system memory in the dashboard?

It gets really hard to read anything meaningful about the apps usage of memory if the system memory is so many orders of magnitude bigger:

<img width="445" alt="screen shot 2017-09-13 at 12 42 26" src="https://user-images.githubusercontent.com/4517582/30389756-cc00f030-9881-11e7-8617-ec045bec0736.png">

(Example from IBM Bluemix 128MB RAM swift instance)

**Comment by tobespc** [comment]
@Bersaelor Hi, yes we have dicsussed this ourselves on doing that.   We are looking at ways of toggling various data items off and on.  Will update as soon as we have decided

**Comment by sjanuary** [comment]
Now fixed
