### ISSUE TITLE
heap-buffer-overflow in SwiftMetrics.receiveAgentCoreData

### ISSUE THREAD

**Issue by djones6** [RuntimeTools/SwiftMetrics#155]
I am working on debugging a crash with Kitura and SwiftMetrics when I apply load to the server.  It crashes on both Linux and OSX, with symptoms that look like a memory corruption issue.

As a starting point, I tried enabling the Address Sanitizer in Xcode.  This reports a problem shortly after starting Kitura (before driving any load).

This is what I get: https://gist.github.com/djones6/50dc7f9eaf53b9b18b0eccfea7fb927b

The offending line seems to be: https://github.com/RuntimeTools/SwiftMetrics/blob/1.2.4%40swift-4/Sources/SwiftMetrics/SwiftMetrics.swift#L72

One suspicious thing here is that it appears not to be using the `cSize` parameter, other than to check the size is > 0.  Also, I believe the String initialiser looks for a null terminator; perhaps the data passed in is not correctly null terminated?

**Comment by djones6** [comment]
Adding a null terminator to the end of the data seems to fix the problem (address sanitizer no longer complains).

Eg: https://github.com/djones6/SwiftMetrics/commit/83a884c7ff26f9552ff21b0a6b6d6ba864a32c94

**Comment by seabaylea** [comment]
@djones6 Is there a PR for this?

**Comment by djones6** [comment]
My change above addresses the symptom but I am not convinced it's the right fix.  I'm looking at it further with @sjanuary

**Comment by djones6** [comment]
The monitoring data sources _were_ adding a null terminator to their data, but did not add 1 to the buffer size to account for the terminator, and so it was lost as soon as the data was copied.

RuntimeTools/omr-agentcore#60 and RuntimeTools/SwiftMetrics#157 resolve this for Swift 4 and 3.1.1 respectively.
