### ISSUE TITLE
Can't currently build on Linux due to OpenSSL library conflict

### ISSUE THREAD

**Issue by Fryie** [RuntimeTools/SwiftMetrics#200]
When trying to build the master branch with Swift 4.2 on Linux, I get the following error during package resolution:

```
error: multiple targets named 'OpenSSL' in: OpenSSL, SSLService
```

It seems that in the transitive dependencies of this package there are multiple targets called `OpenSSL`. One of them seems to have been introduced just recently in [BlueSSLService](https://github.com/IBM-Swift/BlueSSLService/pull/57/commits/3805a5263cec43744045a1b632871aba62b05e5e).

**Comment by ianpartridge** [comment]
Hi, I think this was fixed in https://github.com/IBM-Swift/BlueSSLService/commit/0a745d8cb96c9076f42beeafbf98a2ab3a64e001 - please reopen if you are still having problems. Thanks.
