### ISSUE TITLE
Remove SwiftyRequest

### ISSUE THREAD

**Issue by ianpartridge** [RuntimeTools/SwiftMetrics#203]
SwiftyRequest is used for outbound HTTP requests in a few places.
- https://github.com/RuntimeTools/SwiftMetrics/blob/a8eccd530b03c3270b798f05dbd9dc838d21f56c/Sources/SwiftBAMDC/SwiftMetricsBAMConfig.swift#L549
- https://github.com/RuntimeTools/SwiftMetrics/blob/2d76575bf9b239a949aaf418aaba869be863a181/Sources/SwiftMetricsBluemix/SwiftMetricsBluemix.swift#L389
- https://github.com/RuntimeTools/SwiftMetrics/blob/2d76575bf9b239a949aaf418aaba869be863a181/Sources/SwiftMetricsBluemix/SwiftMetricsBluemix.swift#L409
- https://github.com/RuntimeTools/SwiftMetrics/blob/2d76575bf9b239a949aaf418aaba869be863a181/Sources/SwiftMetricsBluemix/SwiftMetricsBluemix.swift#L426

If we used `URLSession` directly we could remove the dependency on SwiftyRequest which would simplify the package graph and improve build times.

**Comment by vldmrkl** [comment]
I can work on it if you don't mind.

**Comment by ShihabMehboob** [comment]
PR open: https://github.com/RuntimeTools/SwiftMetrics/pull/204

**Comment by ianpartridge** [comment]
Fixed in https://github.com/RuntimeTools/SwiftMetrics/pull/204
