### ISSUE TITLE
Memory value for bluemix is not correct.

### ISSUE THREAD

**Issue by qibobo** [RuntimeTools/SwiftMetrics#21]
When working with Auto-Scaling, the app only owns 256m but the agent report memory more than 1200m.

**Comment by stalleyj** [comment]
I've checked that the value that we are returning is what we expect. We are calculating the process memory as the difference between the virtual process size (using /proc/<pid>/statm) and the shared memory size (using /proc/<pid>/stat). It is not clear why this is not giving a sensible value in Bluemix

**Comment by cdlliuy** [comment]
Please note the memory quota of the app is 256MB, but the agent reported metric usage is 1200MB.   It is unacceptable result. 

If the memory value can't be consistent with "cf memory" value,  we will stop to use the memory metric reported by swift agent.

**Comment by stalleyj** [comment]
I have changed the memory value that we are passing to the auto-scaling service to be the physicalRAMUsed.

**Comment by tobespc** [comment]
can this be tested please ?

**Comment by qibobo** [comment]
@tobespc @stalleyj  Please refer the mail I sent to you both on Feb 17.

**Comment by tobespc** [comment]
Can we resolve this issue in here please and not use email.   The values we are giving are consistent with how we report memory for all our runtimes. @qibobo  please can you update after testing with the latest version of swift metrics

**Comment by qibobo** [comment]
@tobespc Currently the gap between "cf app" and agent is consistent and we think it is acceptable. So we can close this issue now.
