### ISSUE TITLE
Use KituraSocketIO for transmission of data in the dashboard

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#22]
Need to swap using rest calls to pull data and swap to websockets to push data to the dashboard

Package KituraWebSocket to be used

**Comment by rolivieri** [comment]
@tobespc Is there an ETA on when this will be available? Just following up mainly because of the issue we are seeing: https://github.com/RuntimeTools/SwiftMetrics/issues/19

**Comment by tobespc** [comment]
we are going ahead with KituraWebSocket for now, should be ready this week

**Comment by tobespc** [comment]
This is complete and KituraWebSockets is now being used for all transmission
