### ISSUE TITLE
Apparent memory leak when using SwiftMetrics

### ISSUE THREAD

**Issue by TheSoundDefense** [RuntimeTools/SwiftMetrics#26]
When incorporating SwiftMetrics into our Swift Enterprise Demo project and pushing it to CloudFoundry, we noticed memory usage slowly increasing over time (by a megabyte every five to ten minutes or so, if I'm remembering correctly). This memory usage disappeared when pushing the application without SwiftMetrics. This is significant since the Swift Enterprise Demo depends on memory usage being fairly tightly controlled.

**Comment by tobespc** [comment]
@TheSoundDefense We do use memory in swiftmetrics, particularly with the dashboard as we are caching data each time before we transmit.  We are investigating our memory usage at the moment so will update shortly with results

**Comment by rolivieri** [comment]
@tobespc Hey, any updates on this issue?

**Comment by tobespc** [comment]
in progress, got sidetracked with fixing the issues with the node dashboard

**Comment by tobespc** [comment]
in progress still, we had to work on the node dashboard for a while but back on this this week

**Comment by rolivieri** [comment]
@tobespc Thanks for the update above. Do you think we will get a fix sometime this week or early next week?

**Comment by tobespc** [comment]
@rolivieri so, we are implementing useing websockets for the transmission of data which will fix this issue.  Have a prototype working right now and will hope to have it complete by end of this week.  I'll let you know when its ready (currently not in fit state to show anyone lol) but it will be ready for interconnect

**Comment by TheSoundDefense** [comment]
@tobespc It looks like the two crash-related issues have been taken care of, which is great; I was able to run the dashboard for two hours without any issues. It seems like this memory leak is still present, though; I can see the memory slowly increase after pushing it to Bluemix. Do we have an ETA on fixing this issue? Thanks.

**Comment by tobespc** [comment]
It seems this memory leak is only occuring when we attach the autoscaling service.  I don't see it without

**Comment by stalleyj** [comment]
@TheSoundDefense @rolivieri Can you confirm whether it is the Swift Process or System memory that you see increasing and also if the problem occurs with or without the Auto Scaling service connected ?

**Comment by TheSoundDefense** [comment]
I'm not entirely sure how to identify one or the other. What I'm looking at is the "application RAM  used" parameter obtained from SwiftMetrics. When I remove the auto-scaling service, I can still see some fluctuations in the memory, but it doesn't appear to be the steady increase that we observed previously. I can see it increasing by 4 MB or so at one point, staying there a long time, then dropping by another 2 MB or so. I'll check again in an hour or so but it doesn't seem to be the memory leak.

**Comment by tobespc** [comment]
Looks like we are creating JSON objects when we don't need to, I'm putting a change in that stops doing this unnecessary work.
