### ISSUE TITLE
Response time is not accurate

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#3]
Raised from 

https://github.com/IBM-Swift/SwiftMetrics/issues/48

**Comment by stalleyj** [comment]
The response time that SwiftMetrics is passing to the Auto scaling service is an average of all responses over the 30 second window. Are you comparing this to an average or just the last reponse time reported in the cf logs ?

**Comment by stalleyj** [comment]
@qibobo Any thought on this ?

**Comment by stalleyj** [comment]
I have done some testing and confirmed with the Swift team that we are accurately reporting the http response time.  We measure this as the difference between the time the request is received by Kitura.net and the time the request has finished processing.  Could the difference here be that cf router is reporting time outside of Kitura ?

**Comment by tobespc** [comment]
@qibobo  please can you respond to the question above so that we can resolve this as soon as possible.  Thanks

**Comment by qibobo** [comment]
@tobespc @stalleyj  Please refer the mail I sent to you both on Feb 17.

**Comment by tobespc** [comment]
We will add dispatch queue monitoring under issue #33 and send this value along with the kitura response.  As such, I'm going to close this issue as the response time we currently send is correct but its a smaller piece of what is needed.  #33 will be used to track this from now on
