### ISSUE TITLE
Add monitoring of dispatch queue delay

### ISSUE THREAD

**Issue by seabaylea** [RuntimeTools/SwiftMetrics#33]
In the same way that we monitor the event loop delay on Node.js, we should do the same for Swift for the dispatch queue delay. Kitura schedules its work onto the global queue, so no integration with Kitura should be required to monitor the dispatch queue is uses.

**Comment by qibobo** [comment]
@mattcolegate @stalleyj  Could the delay be printed out in log?

**Comment by tobespc** [comment]
@qibobo We wouldn't put this out in a log, if its important enough to monitor then we would have it displayed in the dashboard and available as a metric available through the api

**Comment by tobespc** [comment]
Will investigate this today

**Comment by tobespc** [comment]
@mattcolegate Matt, can you update with progress please as you make some please

**Comment by mattcolegate** [comment]
Created a latency metric by putting work on the dispatch queue with a start time, then determining the latency by comparing that start time with the time of execution of the work. Added a 2 second sleep delay so we're not spamming the dispatch queue.
