### ISSUE TITLE
Segfault if dashboard is left open

### ISSUE THREAD

**Issue by TheSoundDefense** [RuntimeTools/SwiftMetrics#34]
After including SwiftMetrics into our SwiftEnterpriseDemo program, we've noticed that it will occasionally segfault if you are running the program in macOS and if you have the SwiftMetrics dashboard currently open in your browser. It doesn't seem to happen if the dashboard is not open, and I couldn't make it happen at all in Linux.

I ran the program in LLDB and this is the output that I got from that upon crashing:

```Process 46285 stopped
* thread #8: tid = 0x67eb6, 0x00000001007779fb libswiftCore.dylib`swift_unknownRetain + 27, queue = 'requestStoreQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x30b1bcba)
    frame #0: 0x00000001007779fb libswiftCore.dylib`swift_unknownRetain + 27
libswiftCore.dylib`swift_unknownRetain:
->  0x1007779fb <+27>: andq   (%rdi), %rax
    0x1007779fe <+30>: testb  $0x1, 0x20(%rax)
    0x100777a02 <+34>: je     0x100777a0a               ; <+42>
    0x100777a04 <+36>: testb  $0x2, 0x28(%rax)
```

`requestStoreQueue` appears to be referring to a DispatchQueue in SwiftMetricsKitura.swift. Hopefully this is a useful starting point for you guys.

**Comment by tobespc** [comment]
@TheSoundDefense Thanks for the info, will get on this today

**Comment by rolivieri** [comment]
@tobespc Are there any updates on this? Do you think we will get a fix before InterConnect?

**Comment by tobespc** [comment]
@rolivieri so, we are implementing useing websockets for the transmission of data which will fix this issue.  Have a prototype working right now and will hope to have it complete by end of this week.  I'll let you know when its ready (currently not in fit state to show anyone lol) but it will be ready for interconnect
