### ISSUE TITLE
Turn MQTT off by default

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#38]
The main use case of SwiftMetrics will either be for visualising the data through the embedded dashboard of by accessing the data through the API.  As such, there is no need to have the code try and start an MQTT connection by default.  This will still be there for enabling through the properties file should it be required

**Comment by mattcolegate** [comment]
This also needs a change to agentcore; the properties file has mqtt on by default.

**Comment by tobespc** [comment]
adding new swiftmetrics.properties file to default to off
