### ISSUE TITLE
The mem.timeOfSample and cpu.timeOfSample are quite different even running at the same time.

### ISSUE THREAD

**Issue by qiyaod** [RuntimeTools/SwiftMetrics#45]
This is a custom Memory event response.
mem.timeOfSample = 1487310983002,
mem.totalRAMOnSystem = 17179869184,
mem.totalRAMUsed = 14667137024,
mem.totalRAMFree = 2512732160,
mem.applicationAddressSpaceSize = 2613043200,
mem.applicationPrivateSize = -1,
mem.applicationRAMUsed = 9957376.

POST request got response 202
POST request got response 202

This is a custom CPU event response.
cpu.timeOfSample = 9967027531565,
cpu.percentUsedByApplication = 0.00287353,
cpu.percentUsedBySystem = 0.0.

**Comment by mattcolegate** [comment]
This does not appear to happen on the latest SwiftMetrics running the common sample:

This is a custom CPU event response.
 cpu.timeOfSample = 1487779569339, 
 cpu.percentUsedByApplication = 0.0, 
 cpu.percentUsedBySystem = 0.0899307.


This is a custom Memory event response.
 mem.timeOfSample = 1487779569338, 
 mem.totalRAMOnSystem = 2097700864, 
 mem.totalRAMUsed = 1762742272, 
 mem.totalRAMFree = 334958592, 
 mem.applicationAddressSpaceSize = 641454080, 
 mem.applicationPrivateSize = 622923776, 
 mem.applicationRAMUsed = 22941696.


This is a custom CPU event response.
 cpu.timeOfSample = 1487779572342, 
 cpu.percentUsedByApplication = 0.0, 
 cpu.percentUsedBySystem = 0.106571.


This is a custom Memory event response.
 mem.timeOfSample = 1487779572341, 
 mem.totalRAMOnSystem = 2097700864, 
 mem.totalRAMUsed = 1762742272, 
 mem.totalRAMFree = 334958592, 
 mem.applicationAddressSpaceSize = 641454080, 
 mem.applicationPrivateSize = 622923776, 
 mem.applicationRAMUsed = 22941696.

Are you on the latest SwiftMetrics?

**Comment by mattcolegate** [comment]
Had a hunch and checked it out - you are correct, this is a macOS only issue in the way we report CPU time of sample. My suspicion is that it's in agentcore... will investigate.

**Comment by qiyaod** [comment]
Ok, will close this issue. If still see the problem with latest SwiftMetrics will reopen it. Thanks for quick check!

**Comment by mattcolegate** [comment]
This issue has now been fixed in https://github.com/RuntimeTools/omr-agentcore/pull/31 - please delete your Packages directory and rebuild. Make sure when cloning dependencies you get omr-agentcore 3.1.1 or above.
