### ISSUE TITLE
Metric to obtain total memory available to Bluemix instance

### ISSUE THREAD

**Issue by TheSoundDefense** [RuntimeTools/SwiftMetrics#57]
@tobespc At the moment, we are using the `totalRAMOnSystem` metric to determine the total amount of memory available for an instance of the SwiftEnterpriseDemo application running on Bluemix. The amount of memory given from this metric is about 32 GB, but the amount of memory available to the application is only 256 MB. Is this a defect, or is there another metric we should be reading to obtain the maximum memory allowed for the application instance? Can another metric be created for this?

**Comment by rolivieri** [comment]
I now wonder if this issue we are seeing in related to this one: https://github.com/RuntimeTools/SwiftMetrics/issues/21

**Comment by qibobo** [comment]
@rolivieri @TheSoundDefense  For #21, it is about the app's used memory, while for this issue, I think @TheSoundDefense means the memory quota of a bluemix application.

**Comment by TheSoundDefense** [comment]
Right, we were unsure if SwiftMetrics was supposed to obtain the memory quota of a Bluemix application. If not, is that something that can be done?

**Comment by rolivieri** [comment]
@qibobo I see, thanks for the info!

@TheSoundDefense Let's see what @tobespc says regarding this and SwiftMetrics. If SwiftMetrics is not meant to provide this value, we could then get it through VCAP_APPLICATION: https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION. Specifically, the limits field. Swift-cfenv makes this value available to the app: https://github.com/IBM-Swift/Swift-cfenv.

**Comment by tobespc** [comment]
@TheSoundDefense  We don't provide the value of the bluemix environment but we could do if it was a requirement.  We could provide all the information available from swift-cfenv is that was needed

**Comment by rolivieri** [comment]
@tobespc Got you, no new requirement from us at the moment. We can close this issue, thanks.
