### ISSUE TITLE
Push SwiftMetricsLatency into SwiftMetrics

### ISSUE THREAD

**Issue by mattcolegate** [RuntimeTools/SwiftMetrics#63]
As discussed with @tobespc , he raises the very good point that having a dispatch queue isn't something one can opt out of, and therefore we shouldn't have to enable that monitoring - it should be on by default. To accomplish this, I will merge the contents of SwiftMetricsLatency into SwiftMetrics.

**Comment by qibobo** [comment]
@mattcolegate @tobespc  The latency value is very small (0.002ms) while the gap between agent's response time and cf-router&jmeter's is more than 15 seconds.

**Comment by mattcolegate** [comment]
@qibobo please provide detailed instructions and relevant files for your testcase.

**Comment by qibobo** [comment]
my test app : https://github.com/qibobo/qiyeswiftagentdemo

**Comment by mattcolegate** [comment]
There are no mentions of cf router or jmeter on that page. Please provide detailed instructions for your testcase.

**Comment by qibobo** [comment]
@mattcolegate testSwiftAgent.jmx is the jmeter file and for cf router response time value, use cf logs appName --recent | grep response_time to view it.

**Comment by mattcolegate** [comment]
So is `jmeter testSwiftAgent.jmx` sufficient? Where is it expecting the test code to be located? In what directory do I run it?

**Comment by mattcolegate** [comment]
@qibobo, @tobespc makes the very good point that this is way off topic for the actual issue raised here - let's continue this in #70.
