### ISSUE TITLE
Auto-scaling agent's reported response time is not as expected

### ISSUE THREAD

**Issue by mattcolegate** [RuntimeTools/SwiftMetrics#70]
The auto-scaling agent is reporting response times some 15-20ms faster than methods used by the auto-scaling service team (cf router output, jmeter output). It was hoped that adding in Dispatch Queue latency would go some way towards plugging that gap, but that is being reported in the microsecond range.

The auto-scaling service team's testcase is found here: https://github.com/qibobo/qiyeswiftagentdemo

For cf router response time value, use cf logs appName --recent | grep response_time to view it.

For the jmeter output:

- Clone the above repository, build it using swift build, deploy to bluemix (edit the manifest.yml to set an appropriate doman) (default logging is Info, update Sources/swiftdemo/main.swift to change level)
- Aquire and unzip a copy of JMeter (http://jmeter.apache.org/download_jmeter.cgi)
- Download a copy of the jmeter plugins manager and install as instructed (https://jmeter-plugins.org/downloads/all/)
- Open the JMeter GUI using `bin/jmeter`, go to Options -> Plugins Manager and make sure the 'jpgc - Standard Set' plugin is installed.
- Load testSwiftAgent.jmx into Jmeter
- Disable all tests in the test plan (right-click the cogs, select Disable). Enable addSynchronize. Check the web server name in the HTTP Request for addSynchronize is pointing to the deployed Bluemix app URL.
- (Optional) Right-click 'Clear' the View Results in Table and View Results in Tree.
-  Run the test by Right-click 'Start'. Results can be seen by clicking View Results in Table and in the cf log output. Remember that the test has a 10-second ramp up period!

[edited when I worked out how to run tests]

**Comment by mattcolegate** [comment]
The logs from my test session can be found here: 
[logs.txt](https://github.com/RuntimeTools/SwiftMetrics/files/838303/logs.txt)
I've trimmed them to just the HTTP timings we're interested in here:
[timing_logs.txt](https://github.com/RuntimeTools/SwiftMetrics/files/838305/timing_logs.txt)

There seems to be some order-of-magnitude difference between the raw numbers, which may be throwing off calculations. I'll follow the data through and see for sure.

**Comment by mattcolegate** [comment]
I've followed the numbers through and it is accurate - what's being reported in the ResponseTime metric from the agent is definitely in ms, and in my test run it was somewhere between 9000 and 10000 ms (9 to 10 seconds. The logs above corroborate this.

**Comment by mattcolegate** [comment]
Having mathematically analysed the 25 samples contained in the above logs, I can say that on average the agent responseTime was within a 2ms difference to the time observed by jmeter, with a standard deviation of 3ms, and within 7ms difference to the time observed by cf router with a standard deviation of 6ms. I don't believe that this difference is enough to affect the decision of whether to spawn another instanceof the application. My conclusion is that this is accurate enough for the Auto-Scaling service team to use for their responseTime metrics.

As an addendum, I don't know why the cf router and jmeter timing outputs are in seconds....?

**Comment by mattcolegate** [comment]
@qibobo, take a look and reopen if you disagree, with detailed instructions on how to run the test so that a much more significant deviation is output.

**Comment by sjanuary** [comment]
https://github.com/RuntimeTools/SwiftMetrics/pull/77 may improve timing metrics as I think global dispatch queue latency was previously being measured incorrectly.  It would be worth retesting after that has been merged.

**Comment by cdlliuy** [comment]
@sjanuary , thanks for the commit. Yes, it did improved the accuracy of  response time metric.  It is acceptable for us now.
