### ISSUE TITLE
Lost debugging info

### ISSUE THREAD

**Issue by superman9740** [RuntimeTools/SwiftMetrics#84]
After adding your package, when I’m debugging, I don’t get any debug info.  If I try to po a variable, I get "warning: Swift error in module SwiftMetricsKitura.
Debug info from this module will be unavailable in the debugger."
This is in Xcode on macOS. If I remove your package and rebuild, the issue goes away.  I’m wondering if it’s because you have a mix of Swift and C++.  IIRC, Xcode 8 had an issue when mixing frameworks with different swift versions. Maybe there’s an issue with different languages as well.

After researching this a bit, could also have to do with umbrella directories in a modulemap.
https://bugs.swift.org/browse/SR-3200

**Comment by mattcolegate** [comment]
We've done some testing using lldb and this doesn't seem to be an issue if you're just using the basic SwiftMetrics module, so our current theory is that this is to do with a similar problem being investigated in Kitura https://github.com/IBM-Swift/SwiftRuntime/issues/252 which is imported by the SwiftMetricsKitura module. We'll be awaiting a fix in Kitura then updating our Package.swift to pull it in. We've not done a lot with Xcode but we're now attempting to ramp this up!
