### ISSUE TITLE
Average Response Time Chart does not trim path names

### ISSUE THREAD

**Issue by vincent-coetzee** [RuntimeTools/SwiftMetrics#93]
The bar chart that displays the top 5 average response times does not properly display the names of the paths. I realize that this is a minor visual issue but it does limit the utility of the dashboard. They are squashed if they are too long and they overwrite the percentages. I attach a graphic to display what I mean. Perhaps if a path is too long, the first section of the path ( up to a / ) could be displayed then an ellipsis, and then the last part of the path, something along the lines of /shnapped/.../image/fetch or even .../image/fetch.

![server](https://cloud.githubusercontent.com/assets/12059694/24827184/21e29160-1c46-11e7-96cb-b8f3c02407f1.jpeg)

**Comment by mattcolegate** [comment]
Agree with the comments made, perhaps we can add a tooltip to display the full path?

**Comment by sjanuary** [comment]
I think we already have a tooltip so any kind of truncation would work although I prefer keeping the end of the URL e.g.  .../image/fetch.

**Comment by tobespc** [comment]
@sjanuary agreed, lets keep the end of the URL and trim the start
