### ISSUE TITLE
System CPU doesn't seem to be working on Mac

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/SwiftMetrics#97]
Getting 0.0 for System CPU usage on MacOS on SwiftMetrics 1.0.1 release.  Process looks ok.

**Comment by tobespc** [comment]
@mattcolegate  can you verify today please

**Comment by mattcolegate** [comment]
Confirmed on MacOS using Swift 3.1 - cpu.percentUsedBySystem consistently 0.0. Investigating.

**Comment by mattcolegate** [comment]
Fixed it - it wasn't actually implemented!
