### ISSUE TITLE
try SwiftMetricsDash(..) never returns if we create our own server

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/SwiftMetrics#98]
`Kitura.run()` never returns by design. If SwiftMetricsDash is instantiated without passing in a Router then it calls Kitura.run and so never returns itself.

At a minimum this should be documented, but I think it would be better if possible to start Kitura asynchronously and then return program control to the user.

**Comment by sjanuary** [comment]
`Kitura.start()` does return so that would be a better alternative at https://github.com/RuntimeTools/SwiftMetrics/blob/master/Sources/SwiftMetricsDash/SwiftMetricsDash.swift#L113

We would need to also stop Kitura when SwiftMetricsDash stops, probably needs a stop() function.

**Comment by mattcolegate** [comment]
Will alter call to Kitura.run() to Kitura.start(), and will add a deinitializer to SwiftMetricsDash that will call Kitura.stop() if we created our own server.
